### ISSUE TITLE
Database async insert for unblocking requests

### ISSUE THREAD

**Issue by aboulay** [octo-technology/tezos-link#70]
Description:
- Insert metrics in an async way with [goroutines](https://www.jaredfolkins.com/how-to-shove-data-into-postgres-using-goroutinesgophers-and-golang/) to avoid waiting for the INSERT response

Estimation: 3

**Comment by frankhillard** [comment]
There is ticket " Add batching and caching of metric insertions #61 " which handle metrics in a cache and push in database every minute and/or every 1000 metrics in cache.

This ticket is a duplicate.... Should be closed
